apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  destination:
    namespace: frontend
    server: https://kubernetes.default.svc
  source:
    path: helm
    repoURL: https://gitlab.com/tha.it.service/tunihealthassitancefrontend
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
